INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '01', 'Ain');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Hauts-de-France', '02', 'Aisne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '03', 'Allier');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Provence-Alpes-Côte d''Azur', '05', 'Hautes-Alpes');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '08', 'Ardennes');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '10', 'Aube');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Normandie', '14', 'Calvados');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '15', 'Cantal');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Nouvelle-Aquitaine', '19', 'Corrèze');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '21', 'Côte-d''Or');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Nouvelle-Aquitaine', '23', 'Creuse');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '25', 'Doubs');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Normandie', '27', 'Eure');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Centre-Val de Loire', '28', 'Eure-et-Loir');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '38', 'Isère');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '39', 'Jura');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '42', 'Loire');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '43', 'Haute-Loire');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Centre-Val de Loire', '45', 'Loiret');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '51', 'Marne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '52', 'Haute-Marne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '54', 'Meurthe-et-Moselle');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '55', 'Meuse');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '57', 'Moselle');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '58', 'Nièvre');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Hauts-de-France', '59', 'Nord');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Hauts-de-France', '60', 'Oise');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Normandie', '61', 'Orne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Hauts-de-France', '62', 'Pas-de-Calais');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '63', 'Puy-de-Dôme');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '67', 'Bas-Rhin');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '68', 'Haut-Rhin');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '69', 'Rhône');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '70', 'Haute-Saône');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '71', 'Saône-et-Loire');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '73', 'Savoie');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Auvergne-Rhône-Alpes', '74', 'Haute-Savoie');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '75', 'Paris');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Normandie', '76', 'Seine-Maritime');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '77', 'Seine-et-Marne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '78', 'Yvelines');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Hauts-de-France', '80', 'Somme');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Nouvelle-Aquitaine', '87', 'Haute-Vienne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Grand Est', '88', 'Vosges');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '89', 'Yonne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Bourgogne-Franche-Comté', '90', 'Territoire de Belfort');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '91', 'Essonne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '92', 'Hauts-de-Seine');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '93', 'Seine-Saint-Denis');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '94', 'Val-de-Marne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H1', 'Île-de-France', '95', 'Val-d''Oise');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Provence-Alpes-Côte d''Azur', '04', 'Alpes-de-Haute-Provence');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Auvergne-Rhône-Alpes', '07', 'Ardèche');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '09', 'Ariège');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '12', 'Aveyron');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '16', 'Charente');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '17', 'Charente-Maritime');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Centre-Val de Loire', '18', 'Cher');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Bretagne', '22', 'Côtes-d''Armor');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '24', 'Dordogne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Auvergne-Rhône-Alpes', '26', 'Drôme');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Bretagne', '29', 'Finistère');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '31', 'Haute-Garonne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '32', 'Gers');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '33', 'Gironde');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Bretagne', '35', 'Ille-et-Vilaine');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Centre-Val de Loire', '36', 'Indre');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Centre-Val de Loire', '37', 'Indre-et-Loire');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '40', 'Landes');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Centre-Val de Loire', '41', 'Loir-et-Cher');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Pays de la Loire', '44', 'Loire-Atlantique');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '46', 'Lot');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '47', 'Lot-et-Garonne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '48', 'Lozère');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Pays de la Loire', '49', 'Maine-et-Loire');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Normandie', '50', 'Manche');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Pays de la Loire', '53', 'Mayenne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Bretagne', '56', 'Morbihan');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '64', 'Pyrénées-Atlantiques');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '65', 'Hautes-Pyrénées');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Pays de la Loire', '72', 'Sarthe');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '79', 'Deux-Sèvres');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '81', 'Tarn');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Occitanie', '82', 'Tarn-et-Garonne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Provence-Alpes-Côte d''Azur', '84', 'Vaucluse');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Pays de la Loire', '85', 'Vendée');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H2', 'Nouvelle-Aquitaine', '86', 'Vienne');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Provence-Alpes-Côte d''Azur', '06', 'Alpes-Maritimes');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Occitanie', '11', 'Aude');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Provence-Alpes-Côte d''Azur', '13', 'Bouches-du-Rhône');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Corse', '2A', 'Corse-du-Sud');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Corse', '2B', 'Haute-Corse');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Occitanie', '30', 'Gard');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Occitanie', '34', 'Hérault');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Occitanie', '66', 'Pyrénées-Orientales');
INSERT INTO departements_zones (Zone, Region, Code, Nom) VALUES ('H3', 'Provence-Alpes-Côte d''Azur', '83', 'Var');
